version: '3.8'

services:

  dashboard:
    build: ../app
    container_name: parkshare_dashboard
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - sqlite_data:/app/database
    networks:
      - web

volumes:
  sqlite_data:

networks:
  web:
